services:
  hello-world:
    image: alpine:latest
    restart: unless-stopped
    command: sh -c "while true; do echo 'hello world'; sleep 1; done"
    env_file:
      - .env
  hello-world2:
    image: alpine:latest
    restart: unless-stopped
    command: sh -c "while true; do echo 'hello world2'; sleep 1; done"
    env_file:
      - .env